# Generated by Django 5.1.2 on 2024-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('borrower_name', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('loan_number', models.IntegerField(primary_key='loan_number', serialize=False)),
            ],
        ),
    ]
